// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/command.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Echo struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Echo) Reset()         { *m = Echo{} }
func (m *Echo) String() string { return proto.CompactTextString(m) }
func (*Echo) ProtoMessage()    {}
func (*Echo) Descriptor() ([]byte, []int) {
	return fileDescriptor_44263836b6ea8428, []int{0}
}

func (m *Echo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Echo.Unmarshal(m, b)
}
func (m *Echo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Echo.Marshal(b, m, deterministic)
}
func (m *Echo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Echo.Merge(m, src)
}
func (m *Echo) XXX_Size() int {
	return xxx_messageInfo_Echo.Size(m)
}
func (m *Echo) XXX_DiscardUnknown() {
	xxx_messageInfo_Echo.DiscardUnknown(m)
}

var xxx_messageInfo_Echo proto.InternalMessageInfo

func (m *Echo) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AddUser struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUser) Reset()         { *m = AddUser{} }
func (m *AddUser) String() string { return proto.CompactTextString(m) }
func (*AddUser) ProtoMessage()    {}
func (*AddUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_44263836b6ea8428, []int{1}
}

func (m *AddUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUser.Unmarshal(m, b)
}
func (m *AddUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUser.Marshal(b, m, deterministic)
}
func (m *AddUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUser.Merge(m, src)
}
func (m *AddUser) XXX_Size() int {
	return xxx_messageInfo_AddUser.Size(m)
}
func (m *AddUser) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUser.DiscardUnknown(m)
}

var xxx_messageInfo_AddUser proto.InternalMessageInfo

func (m *AddUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AnyMessage struct {
	Message              *any.Any `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnyMessage) Reset()         { *m = AnyMessage{} }
func (m *AnyMessage) String() string { return proto.CompactTextString(m) }
func (*AnyMessage) ProtoMessage()    {}
func (*AnyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_44263836b6ea8428, []int{2}
}

func (m *AnyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnyMessage.Unmarshal(m, b)
}
func (m *AnyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnyMessage.Marshal(b, m, deterministic)
}
func (m *AnyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnyMessage.Merge(m, src)
}
func (m *AnyMessage) XXX_Size() int {
	return xxx_messageInfo_AnyMessage.Size(m)
}
func (m *AnyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AnyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AnyMessage proto.InternalMessageInfo

func (m *AnyMessage) GetMessage() *any.Any {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*Echo)(nil), "pb.Echo")
	proto.RegisterType((*AddUser)(nil), "pb.AddUser")
	proto.RegisterType((*AnyMessage)(nil), "pb.AnyMessage")
}

func init() { proto.RegisterFile("pb/command.proto", fileDescriptor_44263836b6ea8428) }

var fileDescriptor_44263836b6ea8428 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x48, 0xd2, 0x4f,
	0xce, 0xcf, 0xcd, 0x4d, 0xcc, 0x4b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48,
	0x92, 0x92, 0x4c, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x8b, 0x24, 0x95, 0xa6, 0xe9, 0x27,
	0xe6, 0x55, 0x42, 0xa4, 0x95, 0x14, 0xb8, 0x58, 0x5c, 0x93, 0x33, 0xf2, 0x85, 0x24, 0xb8, 0xd8,
	0x73, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x60, 0x5c,
	0x25, 0x59, 0x2e, 0x76, 0xc7, 0x94, 0x94, 0xd0, 0xe2, 0xd4, 0x22, 0x21, 0x21, 0x2e, 0x96, 0xbc,
	0xc4, 0x5c, 0x98, 0x0a, 0x30, 0x5b, 0xc9, 0x86, 0x8b, 0xcb, 0x31, 0xaf, 0xd2, 0x17, 0xa2, 0x58,
	0x48, 0x0f, 0xd5, 0x18, 0x6e, 0x23, 0x11, 0x3d, 0x88, 0xdd, 0x7a, 0x30, 0xbb, 0xf5, 0x1c, 0xf3,
	0x2a, 0xe1, 0x86, 0x27, 0xb1, 0x81, 0x85, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x23,
	0x3e, 0x13, 0xb8, 0x00, 0x00, 0x00,
}
