// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/command.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Echo struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Echo) Reset()         { *m = Echo{} }
func (m *Echo) String() string { return proto.CompactTextString(m) }
func (*Echo) ProtoMessage()    {}
func (*Echo) Descriptor() ([]byte, []int) {
	return fileDescriptor_44263836b6ea8428, []int{0}
}

func (m *Echo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Echo.Unmarshal(m, b)
}
func (m *Echo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Echo.Marshal(b, m, deterministic)
}
func (m *Echo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Echo.Merge(m, src)
}
func (m *Echo) XXX_Size() int {
	return xxx_messageInfo_Echo.Size(m)
}
func (m *Echo) XXX_DiscardUnknown() {
	xxx_messageInfo_Echo.DiscardUnknown(m)
}

var xxx_messageInfo_Echo proto.InternalMessageInfo

func (m *Echo) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Error struct {
	Errorcode            uint32   `protobuf:"varint,1,opt,name=errorcode,proto3" json:"errorcode,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_44263836b6ea8428, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetErrorcode() uint32 {
	if m != nil {
		return m.Errorcode
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AnyMessage struct {
	Message              *any.Any `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnyMessage) Reset()         { *m = AnyMessage{} }
func (m *AnyMessage) String() string { return proto.CompactTextString(m) }
func (*AnyMessage) ProtoMessage()    {}
func (*AnyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_44263836b6ea8428, []int{2}
}

func (m *AnyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnyMessage.Unmarshal(m, b)
}
func (m *AnyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnyMessage.Marshal(b, m, deterministic)
}
func (m *AnyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnyMessage.Merge(m, src)
}
func (m *AnyMessage) XXX_Size() int {
	return xxx_messageInfo_AnyMessage.Size(m)
}
func (m *AnyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AnyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AnyMessage proto.InternalMessageInfo

func (m *AnyMessage) GetMessage() *any.Any {
	if m != nil {
		return m.Message
	}
	return nil
}

type User struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_44263836b6ea8428, []int{3}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LoginReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_44263836b6ea8428, []int{4}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LoginResp struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_44263836b6ea8428, []int{5}
}

func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (m *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(m, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*Echo)(nil), "pb.Echo")
	proto.RegisterType((*Error)(nil), "pb.Error")
	proto.RegisterType((*AnyMessage)(nil), "pb.AnyMessage")
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*LoginReq)(nil), "pb.LoginReq")
	proto.RegisterType((*LoginResp)(nil), "pb.LoginResp")
}

func init() { proto.RegisterFile("pb/command.proto", fileDescriptor_44263836b6ea8428) }

var fileDescriptor_44263836b6ea8428 = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x4e, 0x3d, 0x4b, 0xc5, 0x30,
	0x14, 0xe5, 0x3d, 0xa2, 0xbe, 0x5e, 0x11, 0x24, 0x38, 0x3c, 0x4b, 0x91, 0xd2, 0x49, 0x97, 0x14,
	0x74, 0x15, 0xa4, 0x43, 0x37, 0x5d, 0x02, 0xfe, 0x80, 0xa4, 0x8d, 0x51, 0x30, 0xb9, 0x31, 0xb1,
	0x43, 0xff, 0xbd, 0x34, 0x69, 0xa9, 0x85, 0xb7, 0x9d, 0x8f, 0x7b, 0xcf, 0x39, 0x70, 0xed, 0x64,
	0xdd, 0xa1, 0x31, 0xc2, 0xf6, 0xcc, 0x79, 0xfc, 0x45, 0xba, 0x77, 0x32, 0xbf, 0xd5, 0x88, 0xfa,
	0x5b, 0xd5, 0x51, 0x91, 0xc3, 0x47, 0x2d, 0xec, 0x98, 0xec, 0xaa, 0x04, 0xd2, 0x76, 0x9f, 0x48,
	0x8f, 0x70, 0x61, 0x54, 0x08, 0x42, 0xab, 0xe3, 0xae, 0xdc, 0xdd, 0x67, 0x7c, 0xa1, 0xd5, 0x0b,
	0x9c, 0xb5, 0xde, 0xa3, 0xa7, 0x05, 0x64, 0x6a, 0x02, 0x1d, 0xf6, 0xe9, 0xe8, 0x8a, 0xaf, 0xc2,
	0xff, 0x80, 0xfd, 0x36, 0xe0, 0x19, 0xa0, 0xb1, 0xe3, 0x5b, 0x62, 0x94, 0x6d, 0x8b, 0x2e, 0x1f,
	0x6f, 0x58, 0x5a, 0xc7, 0x96, 0x75, 0xac, 0xb1, 0xe3, 0xfa, 0x9d, 0x03, 0x79, 0x0f, 0xca, 0x53,
	0x0a, 0xc4, 0x0a, 0xb3, 0xac, 0x8b, 0xb8, 0xba, 0x83, 0xc3, 0x2b, 0xea, 0x2f, 0xcb, 0xd5, 0xcf,
	0x49, 0xff, 0x01, 0xb2, 0xd9, 0x0f, 0x8e, 0x16, 0x40, 0x86, 0xa0, 0xfc, 0xdc, 0x7a, 0x60, 0x4e,
	0xb2, 0x29, 0x98, 0x47, 0x55, 0x9e, 0xc7, 0xf6, 0xa7, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd8,
	0xb4, 0x43, 0x99, 0x41, 0x01, 0x00, 0x00,
}
